import type { RouteObject } from 'react-router';
import { ComingSoon } from '@/pages/ComingSoon';

export const publicMainRouteObjects: RouteObject[] = [
  { index: true, element: <ComingSoon title="Home" description="Hero, live counter, flagship carousel and showcase teasers." /> },
  { path: '/map', element: <ComingSoon title="Map" description="District map of clubs and zones." /> },
  { path: '/showcase', element: <ComingSoon title="Showcase" description="Gallery of member and club project posts." /> },
  { path: '/showcase/:slug', element: <ComingSoon title="Showcase post" /> },
  { path: '/showcase/clubs/:clubSlug', element: <ComingSoon title="Club showcase" /> },
  { path: '/heritage', element: <ComingSoon title="Heritage" description="District history and past leadership timeline." /> },
  { path: '/heritage/:slug', element: <ComingSoon title="Heritage entry" /> },
  { path: '/leadership', element: <ComingSoon title="Leadership" description="Current district team." /> },
  { path: '/leadership/clubs/:slug', element: <ComingSoon title="Club leadership" /> },
  { path: '/initiatives', element: <ComingSoon title="Initiatives" description="Flagship district-wide projects." /> },
  { path: '/resources', element: <ComingSoon title="Resources" /> },
  { path: '/resources/documents', element: <ComingSoon title="Documents" /> },
  { path: '/resources/:category', element: <ComingSoon title="Resource category" /> },
  { path: '/resources/guest-kit', element: <ComingSoon title="Guest kit" /> },
  { path: '/resources/sister-club', element: <ComingSoon title="Sister club" description="Sister club request form (requires login in the real build)." /> },
  { path: '/publications', element: <ComingSoon title="Publications" /> },
  { path: '/get-involved/new-club', element: <ComingSoon title="Start a new club" /> },
  { path: '/get-involved/sponsor', element: <ComingSoon title="Become a sponsor" /> },
  { path: '/achievements', element: <ComingSoon title="Achievements" /> },
  { path: '/partners', element: <ComingSoon title="Partners" /> },
  { path: '/contact', element: <ComingSoon title="Contact" /> },
  { path: '/calendar', element: <ComingSoon title="Calendar" /> },
  { path: '/calendar/:slug', element: <ComingSoon title="Event" /> },
  { path: '/drr-calendar', element: <ComingSoon title="DRR calendar" /> },
  { path: '/drr-calendar/book/:slot', element: <ComingSoon title="Book DRR slot" /> },
  { path: '/drr-calendar/admin', element: <ComingSoon title="DRR calendar admin" description="Requires drr_calendar:manage in the real build." /> },
  { path: '/privacy-policy', element: <ComingSoon title="Privacy policy" /> },
  { path: '/terms-of-service', element: <ComingSoon title="Terms of service" /> },
];
